# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
jobs:
    test:
        docker:
            - image: cimg/node:lts-browsers

        working_directory: ~/repo

        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run:
                  name: Test Jest
                  command: make test-ci-jest

            # - run: |
            #       make test-ci-jest

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}

        # "test-e2e": "yarn test-e2e-html && yarn test-e2e-react",
        # "test-e2e-html": "node ../../dev/inc/collect-html-tests.js && start-server-and-test 'cd ../../; yarn dev-server; cd packages/framer-motion' http://localhost:8000 'cypress run -s cypress/tests/appear.ts --config baseUrl=http://localhost:8000/ && cypress run -s cypress/tests/projection.ts --config baseUrl=http://localhost:8000/'",

    test-e2e:
        docker:
            - image: cimg/node:lts-browsers

        working_directory: ~/repo
        parallelism: 4
        steps:
            - checkout

            # Download and cache dependencies
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      # fallback to using the latest cache if no exact match is found
                      - v1-dependencies-

            - run:
                  name: E2E tests
                  command: make test-ci-e2e

            # - run: |
            #       make test-ci-jest

            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}

        # "test-e2e": "yarn test-e2e-html && yarn test-e2e-react",
        # "test-e2e-html": "node ../../dev/inc/collect-html-tests.js && start-server-and-test 'cd ../../; yarn dev-server; cd packages/framer-motion' http://localhost:8000 'cypress run -s cypress/tests/appear.ts --config baseUrl=http://localhost:8000/ && cypress run -s cypress/tests/projection.ts --config baseUrl=http://localhost:8000/'",

workflows:
    version: 2
    build:
        jobs:
            - test
            - test-e2e
